name = "followthrough"
compatibility_date = "2025-12-15"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "followthrough-db2"
database_id = "50b3612a-3e32-4190-acd4-f8a6dbbecfa3"
migrations_dir = "migrations"
[vars]
VITE_API_BASE = "https://essaycoach.alfons149.workers.dev"
