name = "followthrough"
compatibility_date = "2025-12-15"

[[d1_databases]]
binding = "DB"
database_name = "followthrough-db"
database_id = "3YMwhfOYBQYvob3ZOwGHgmr_8CE-QKZkFfUXardE"
migrations_dir = "migrations"
