name = "followthrough"
compatibility_date = "2025-12-15"
account_id = "3YMwhfOYBQYvob3ZOwGHgmr_8CE-QKZkFfUXardE"
[[d1_databases]]
binding = "DB"
database_name = "followthrough-db"
database_id = "e5c51d7d-4c43-4a35-bd78-72a8eb5dc10e"
migrations_dir = "migrations"

