name = "followthrough"
compatibility_date = "2025-12-15"

[[d1_databases]]
binding = "DB"
database_name = "followthrough-db"
account_id = "947c23ef26891789f59af93c859f9dde"
migrations_dir = "migrations"
